### ISSUE TITLE
Consider moving to an organization?

### ISSUE THREAD

**Issue by CarsonF** [jobbyphp/jobby#47]
This would allow much more flexibility in the future. Maintainers could come and go without changing links. See what fabpot has to say about it [here](http://fabien.potencier.org/about-personal-github-accounts.html).

Let me know what you think.

**Comment by hellogerard** [comment]
@CarsonF I like this idea a lot. If you couldn't tell, I don't spend much time on this package anymore because I don't use PHP anymore. But it's still apparently very useful, and I'd like other to be able to contribute easily. I'll try to setup an org and invite you in the next few days (or you can set it up and invite me). 

Do you know Packagist/composer would handle such a change?

**Comment by hellogerard** [comment]
Moved. I may have missed something during the move, so let me know if anyone sees anything.
