### ISSUE TITLE
Jobby & PDO not working

### ISSUE THREAD

**Issue by simivar** [jobbyphp/jobby#56]
Hello,

Could you give me some assistance with Jobby and PDO? I've did eveything like in example and yet it does not work:
http://stackoverflow.com/questions/36479945/jobby-superclosure-not-working-serialization-failed

**Comment by hellogerard** [comment]
Nothing off the top of my head, I'm afraid. When I've encountered that error before, it's usually because I've not loaded or imported some class or type. But I'm sure you've done that.

As a workaround, instead of storing actual code in your database, you could store some metadata about the job and pass it in as parameters at some point. Would that work for your use case?

**Comment by wujekbogdan** [comment]
I have the same issue but I don't use serialisation (or SuperClosure) and I don't store any Jobby-related data in the database. I think that the issue might be related to PDO or SuperClosure itself (which is used by Jobby internally).

**Comment by simivar** [comment]
@wujekbogdan I made a simple change that solved my issue. Right now I do not hold code itself in database (and I should not try that from beggining as it can be dangerous to let people edit code from application itself). I hold only class name and in CRON script all I do is create new object in anonymous function and run defualt method:

    $model = new Model();
    $list = $model->listAll();
    $jobby = new \Jobby\Jobby( $jobbyConfig );

    foreach ( $list as $job )
    {
        $job = array_filter( $job );
        $fn = function () use ( $job )
        {
            $c = new $job[ 'closure' ];
				
            return $c->index();
        };
			
        $job[ 'closure' ] = $fn;
        $jobby->add( $nazwaZadania, $zadanie );
    }

**Comment by wujekbogdan** [comment]
I don't store the cron jobs in the database. My problem is different - I tried to use Jobby closures to execute PDO queries. Jobby called a method that executed PDO internally.

I solved the problem (actually not solved - made a workaround) creating standalone PHP files and executing them using Jobby `command` instead of a `closure`. Not an elegant solution, but at least works.
