### ISSUE TITLE
[Request] ScheduleChecker->isOverdue

### ISSUE THREAD

**Issue by theMajc** [jobbyphp/jobby#69]
I don't quite understand the concept of limiting jobs to the scheduled minute. If the server somehow skipped a bunch of jobs, there's no option to run them again?

Jobby->run() only uses the ScheduleChecker provided isDue() function to compare the current minute to scheduled tasks. I imagine there are needs for this behaviour, but why not provide another option that checks if the scheduled time is behind the current time? 

We have to either delete the jobs ran, or flag them anyways, so it's not like every time Jobby runs it executes all the old jobs again.

I would love to have this built-in rather than having to custom a lot of code outside Jobby to avoid composer update overwrites.

**Comment by hellogerard** [comment]
Jobby runs by comparing the current minute because that is what crontab does. It basically uses crontab's logic. So this probably isn't something we'd put in.

It sounds like you need more of a job queue, which goes hand-in-hand with a crontab/jobby job.  A job would run periodically, check the queue, process jobs on the queue, and remove successful jobs from the queue and place errors back at the end, or something.
