### ISSUE TITLE
Jobby locks task

### ISSUE THREAD

**Issue by jhon50** [jobbyphp/jobby#76]
#Jobby locks current task from repeating while executing
it seems that Jobby lock the current task while it's still being executed, so if the task is supposed to run every minute and it's running at the moment, the next time it should be executed just won't happen until the one before. There is any workaround for this?

**Comment by hellogerard** [comment]
No, this is by design. We don't want multiple instances of the same jobs to overlap, since they usually assume they're running alone. For example, a job that queries a database to get a list of tasks to process. If another job started, and it wasn't written correctly, it might start processing the same task twice.
